### ISSUE TITLE
Use pods for iOS dependency management

### ISSUE THREAD

**Issue by taylorwinfield** [ArmandoAssuncao/react-native-ca-mas#2]
Hey @ArmandoAssuncao 👋 

Really nice work on this lib! It fills a gap I'm having a requirement for at the moment. I've noticed you're using a linked folder `/frameworks` to pull in the CA dependencies on iOS, what do you think of switching to Pods for iOS dependency management and including a `.Podspec` file the same way [react-native-maps](https://github.com/react-community/react-native-maps) handles iOS library dependencies?

**Comment by ArmandoAssuncao** [comment]
Hi @taylorwinfield 

At the moment I'm out of time(who is not? 😄) to add new things in this lib and also have no expertisse on the ecosystem of iOS.
But if it will improve the process of use / installation, feel free to open a PR with this improvement, I will be very happy :-)

**Comment by taylorwinfield** [comment]
Haha I know the feeling! Okay cool, I’ll make some changes on a branch then open a PR with my reasoning and pros/cons and we can decide on it from there. 

Thanks again man, great job!
